apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.appName }}
  # namespace: dev
spec:
  # type: LoadBalancer
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
    # nodePort: 35010
  selector:
    app: {{ .Values.appName }}
status:
  loadBalancer: {}